name: ayah_wa_taamul
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- الحزم الأساسية التي يستخدمها التطبيق أثناء التشغيل ---
  supabase_flutter: ^2.5.0
  google_fonts: ^6.2.1
  flutter_riverpod: ^2.5.1
  share_plus: ^9.0.0
  home_widget: ^0.8.0
  path_provider: ^2.1.3
  workmanager: ^0.9.0+2
  cupertino_icons: ^1.0.8
  screenshot: ^3.0.0
  shared_preferences: ^2.5.3
  connectivity_plus: ^6.1.5
  scrollable_positioned_list: ^0.3.8
  flutter_local_notifications: ^19.4.0
  permission_handler: ^12.0.1
  # flutter_native_timezone: ^2.0.0
  # timezone: ^0.10.1
  
  # ❌ --- تم حذف color و flutter_native_splash من هنا ---

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # ✅ --- المكان الصحيح لحزم التطوير ---
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.6 # ✅ تم نقلها إلى هنا

# ✅ --- قسم إعدادات أيقونة التطبيق (تم تعديل اللون) ---
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#4B0082"     # ✅ تم تصحيح اللون ليتطابق مع الهوية
  adaptive_icon_foreground: "assets/icon/app_icon.png"

# ✅ --- القسم المفقود لإعدادات شاشة البداية (تمت إضافته) ---
flutter_native_splash:
  color: "#2FFFFFF"
  android_12:
    color: "#2FFFFFF"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/